### PR TITLE
Expose ipfs failure to mappings

### LINKED ISSUE #732: Read from IPFS crash the subgraph if hash is invalid/ doesn’t exist
Currently when calling `ipfs.cat` the function will behave as follows:
If the hash is a valid reference to an existing data on IPFS it will return the data.
If the hash queried is invalid or if it points to data which is not stored in the IPFS node it will cause the event listener to crash.

This behavior makes accessing to IPFS reliably practically impossible, as it’s impossible to verify the data exist before sending a query, and in case it indeed doesn’t exist it causes the system to crash.

A possible fix would be to return an empty response in case the query failed.
This would allow to gracefully handle errors and continue the operation of the subgraph.

### PR DESCRIPTION
**Pull request by leoyvens**
Return null if anything goes wrong when fetching a file from IPFS. Also increase the default timeout to 30 seconds and make it configurable through an env var. @davekaj do you want to take this for a spin on a subgraph that needs it as part of the review?

Resolves #732. Part of #748.

### CODE REVIEW

**Comment by davekaj** [comment]
Yes, I'll try it out now

**Comment by davekaj** [comment]
It worked! I’m actually thinking differently now though about the default wait time . It should probably be back to 10 seconds. 30 seconds means we can only get through 120 ipfs cats an hour which is going to make this subgraph sync suuuper slow.

what i proposed in my issue was to have the ipfs stream circle back to the missed ipfs cats, and I think at that point it would be good to let it search for a minute , and cycle through them all, and then search again for two minutes on the next cycle, and keep doing that. maybe up to 10 minutes

because right now for all the 30 second waits, nothing is being found :disappointed:

Are you able to change the default back to 10? Then I think we can merge this

**Comment by leodasvacas** [comment]
@davekaj The default doesn't matter much, we can configure this with an env var.

File: runtime/wasm/src/module/mod.rs [hunk 1]
```diff
@@ -447,9 +447,22 @@ where
...
+        let ipfs_res = self.host_exports.ipfs_cat(link);
+        match ipfs_res {
+            Ok(bytes) => {
+                let bytes_obj: AscPtr<Uint8Array> = self.asc_new(&*bytes);
+                Ok(Some(RuntimeValue::from(bytes_obj)))
+            }
+
+            // Return null in case of error.
+            Err(e) => {
+                info!(self.logger, "Failed ipfs.cat, returning `null`";
```
Comment (Jannis) [inline runtime/wasm/src/module/mod.rs]: I'd be in favor of making this a `warn!`.

**Review by Jannis — APPROVED** [review]

File: runtime/wasm/src/module/mod.rs (hunk 1 above)
Comment (leodasvacas) [reply runtime/wasm/src/module/mod.rs]: My thinking is that for many subgraphs ipfs hashes that cannot be found are just a fact of life, and not something the developer should be concerned about. It might be worth promoting to warn in case of timeouts, which are highly non-deterministic and you can't tell whether the file is accessible.

Comment (leodasvacas) [reply runtime/wasm/src/module/mod.rs]: But I'd have to look into IPFS behaviour to know if we can really differentiate between a file that's not found and a file that took too long to fetch. Lets leave this as a follow up after we observe what these logs look like for real subgraphs.
