### PR TITLE
datasource, graph, mock, store: Fix block ingestor stuck on missing tx

### LINKED ISSUE #491: Block ingestor gets stuck on transactions from uncled blocks
Sometimes a transaction appears in a block, but that block is removed due to a chain reorganization. Usually the transaction will be included in a later block, but not always. In the latter case, the block ingestor might get stuck trying to load a receipt for this transaction.

See also #490

### PR DESCRIPTION
**Pull request by timmclean**
Resolves #491

### CODE REVIEW

**Review by Jannis — DISMISSED** [review]
Looks good!

File: datasource/ethereum/src/block_ingestor.rs [hunk 1]
```diff
@@ -60,10 +60,22 @@ where
...
-                            static_self.logger,
-                            "Trying again after block polling failed: {:?}", e
-                        );
+                        match e {
+                            BlockIngestorError::BlockUnavailable(block_hash) => {
+                                trace!(
+                                    static_self.logger,
+                                    "Trying again after block polling failed: \
+                                    block data unavailable, block was likely uncled";
+                                    "block_hash" => format!("{:?}", block_hash)
```
Comment (leodasvacas) [inline datasource/ethereum/src/block_ingestor.rs]: This should print with `{}` rather than `{:?}`.

File: datasource/ethereum/src/block_ingestor.rs [hunk 2]
```diff
@@ -60,10 +60,22 @@ where
...
+                                );
+                            }
+                            BlockIngestorError::Unknown(e) => {
+                                warn!(
+                                    static_self.logger,
+                                    "Trying again after block polling failed: {:?}", e
```
Comment (leodasvacas) [inline datasource/ethereum/src/block_ingestor.rs]: Same here.

File: datasource/ethereum/src/block_ingestor.rs [hunk 3]
```diff
@@ -262,9 +296,25 @@ where
...
-                .map_err(|e| format_err!("could not get blocks from Ethereum: {}", e))
+                .map_err(|e| format_err!("could not get blocks from Ethereum: {}", e).into())
                 .map(|_| stream::futures_unordered(block_futures))
                 .flatten_stream(),
         )
     }
 }
+
+#[derive(Debug)]
+enum BlockIngestorError {
```
Comment (leodasvacas) [inline datasource/ethereum/src/block_ingestor.rs]: Even though you chose to convert from `Error` to this rather than the other way around, it's still good to derive `Fail` so we get `Display`.

**Review by Jannis — DISMISSED** [review]

File: datasource/ethereum/src/block_ingestor.rs [hunk 4]
```diff
@@ -153,28 +153,66 @@ where
...
+                        if receipt.block_hash != block_hash {
+                            // This block is no longer on the main chain according to the Ethereum
+                            // node.  Nothing we can do from here except give up trying to ingest
+                            // this block.
+                            Err(BlockIngestorError::BlockUnavailable(block_hash))
+                        } else {
+                            Ok(receipt)
+                        }
+                    })
+            }).collect::<Vec<_>>();
```
Comment (leodasvacas) [inline datasource/ethereum/src/block_ingestor.rs]: is this `collect` necessary?

**Review by leoyvens — CHANGES_REQUESTED** [review]
Looks good, a few minor comments.

File: datasource/ethereum/src/block_ingestor.rs (hunk 1 above)
Comment (timmclean) [reply datasource/ethereum/src/block_ingestor.rs]: I used to have that, but H256's Display doesn't print the entire hash :(

File: datasource/ethereum/src/block_ingestor.rs (hunk 4 above)
Comment (timmclean) [reply datasource/ethereum/src/block_ingestor.rs]: I think so, otherwise they'll load serially instead of parallel

File: datasource/ethereum/src/block_ingestor.rs (hunk 3 above)
Comment (timmclean) [reply datasource/ethereum/src/block_ingestor.rs]: Oh good idea. Will do

File: datasource/ethereum/src/block_ingestor.rs (hunk 4 above)
Comment (leodasvacas) [reply datasource/ethereum/src/block_ingestor.rs]: I don't follow, `futures_unordered` would execute in parallel.

File: datasource/ethereum/src/block_ingestor.rs (hunk 1 above)
Comment (leodasvacas) [reply datasource/ethereum/src/block_ingestor.rs]: Ah, what I meant to say is that if we have `Fail` for BlockIngestError then maybe we should not be matching here and instead should just log `e`.

**Comment by timmclean** [comment]
Oh yeah, I see what you're getting at. This match statement is actually why
I made the BlockIngestorError type though -- because I needed to make some
errors `trace` and some errors `warn` -- so I can't really do too much there

File: datasource/ethereum/src/block_ingestor.rs (hunk 4 above)
Comment (timmclean) [reply datasource/ethereum/src/block_ingestor.rs]: Oh good point, those methods collect implicitly don't they. 
So I just tried to remove the collect and the compiler error now reminds me that I collected here to save having to clone. I need `block` later on to move it into the EthereumBlock, so to avoid collecting I would have to clone a bunch anyway, which seemed like a waste...

Comment (leodasvacas) [reply datasource/ethereum/src/block_ingestor.rs]: Weird, well let's not spend too much time on this.

File: datasource/ethereum/src/block_ingestor.rs (hunk 1 above)
Comment (leodasvacas) [inline datasource/ethereum/src/block_ingestor.rs]: This message now duplicates the `Fail` derivation, you can just print `e` instead.

**Review by leoyvens — CHANGES_REQUESTED** [review]

**Comment by Jannis** [comment]
@leodasvacas How's this looking now?

**Comment by leodasvacas** [comment]
@Jannis my only remaining comment is https://github.com/graphprotocol/graph-node/pull/492#discussion_r226123682

**Comment by Jannis** [comment]
Ah, yes, sorry, that is still valid.

**Comment by timmclean** [comment]
@leodasvacas Fixed!

**Review by leoyvens — APPROVED** [review]
