### PR TITLE
Derived fields should respect causality region + Improve tests

### LINKED ISSUE #5267: [Bug] Derived loaders does not respect causality regions
### Bug report

Derived loaders are not respecting causality regions.
Entities created by file data sources are not allowed to be loaded from an onchain handler but it can be loaded when entities are linked via a derived field in another entity. 

### Relevant log output

_No response_

### IPFS hash

_No response_

### Subgraph name or link to explorer

_No response_

### Some information to help us out

- [ ] Tick this box if this bug is caused by a regression found in the latest release.
- [ ] Tick this box if this bug is specific to the hosted service.
- [X] I have searched the issue tracker to make sure this issue is not a duplicate.

### OS information

None

### PR DESCRIPTION
**Pull request by incrypto32**
Closes #5267

### CODE REVIEW

File: graph/src/components/store/mod.rs [hunk 1]
```diff
@@ -90,6 +90,7 @@ impl DerivedEntityQuery {
     /// Checks if a given key and entity match this query.
     pub fn matches(&self, key: &EntityKey, entity: &Entity) -> bool {
         key.entity_type == self.entity_type
+            && key.causality_region == self.causality_region
```
Comment (zorancv) [inline graph/src/components/store/mod.rs:93]: Love short implementations!

File: tests/runner-tests/file-data-sources/src/mapping.ts [hunk 2]
```diff
@@ -4,130 +4,148 @@ import {
...
+  let context = dataSource.context();
+
+  if (context.isSet("command")) {
+    let contextCommand = context.getString("command");
+
+    if (contextCommand == SPAWN_FDS_FROM_OFFCHAIN_HANDLER) {
+      let hash = context.getString("hash");
+      log.info("Creating file data source from handleFile: {}", [hash]);
+      dataSource.createWithContext("File", [hash], new DataSourceContext());
+    }
```
Comment (zorancv) [inline tests/runner-tests/file-data-sources/src/mapping.ts:120]: Not sure what's idiomatic for TypeScript bu wouldn't `else if` look more like a switch statement?

**Review by zorancv — APPROVED** [review]
Cool that we can do a test with a blockchain!

File: tests/runner-tests/file-data-sources/src/mapping.ts [hunk 3]
```diff
@@ -4,130 +4,148 @@ import {
...
+
+    if (contextCommand == CREATE_FOO) {
+      log.info("Creating FileEntity with relation to Foo", []);
+      let entity = new FileEntity(dataSource.stringParam());
+      entity.foo = dataSource.stringParam();
+      entity.content = data.toString();
+      entity.save();
+    }
+  } else {
```
Comment (mangas) [inline tests/runner-tests/file-data-sources/src/mapping.ts:141]: Can remove a nesting level by doing this block if not command and returning. Then you know all the rest are commands. as zoran said it's prolly more of a switch case, mostly for making it a bit easier to maintain and read if you think it's worth. But also none of the ifs return when match so that could create some weird test situations :laughing:

File: tests/runner-tests/file-data-sources/src/mapping.ts (hunk 2 above)
Comment (incrypto32) [reply tests/runner-tests/file-data-sources/src/mapping.ts:120]: Agree, it should have been an else if.

We cannot use switch cases though since switch-case in assemblyscript does not work with string
https://github.com/AssemblyScript/assemblyscript/issues/1643

File: tests/runner-tests/file-data-sources/src/mapping.ts (hunk 3 above)
Comment (incrypto32) [reply tests/runner-tests/file-data-sources/src/mapping.ts:141]: Agreed, making the change.
