### PR TITLE
ethereum: Detect out of gas as call revert

### LINKED ISSUE #2516: Trying again after eth_call RPC call failed "out of gas" [Ethereum Mainnet]
**Do you want to request a *feature* or report a *bug*?**

Possibly a bug, AFAICT.

**What is the current behavior?**

Subgraph synchronization stuck with an 'Trying again after eth_call RPC call failed' warning message.

The issue produces ServerError(-32000) "out of gas" on the Ethereum mainnet.

Here is the full warning message:

```
Trying again after eth_call RPC call failed (attempt #10) with result Err(Web3Error(Rpc(Error { code: ServerError(-32000), message: "out of gas", data: None }))), block_hash: 0xf39eb489773304ba7906e9ad896b6fd13f8e1d369c3ab6b0c74622769e1c9975, block_number: 5258109
```

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**

Just check the logs (with WARN filter) for the following subgraph:

https://thegraph.com/explorer/subgraph/nftfy/nftfy-v1-mainnet

I am just trying to sync that particular subgraph.

**What is the expected behavior?**

Unless I am missing something, the subgraph synchronization should progress on.

### PR DESCRIPTION
**Pull request by leoyvens**
Resolves #2516.

### CODE REVIEW

File: chain/ethereum/src/ethereum_adapter.rs [hunk 1]
```diff
@@ -99,6 +99,7 @@ lazy_static! {
     /// It is not safe to set something higher because Geth will silently override the gas limit
     /// with the default. This means that we do not support indexing against a Geth node with
     /// `RPCGasCap` set below 25 million.
+    //// See also f0af4ab0-6b7c-4b68-9141-5b79346a5f61.
```
Comment (otaviopace) [inline chain/ethereum/src/ethereum_adapter.rs:102]: Minor, extra slash here.

**Review by otaviopace — APPROVED** [review]

File: chain/ethereum/src/ethereum_adapter.rs [hunk 2]
```diff
@@ -99,6 +99,7 @@ lazy_static! {
     /// It is not safe to set something higher because Geth will silently override the gas limit
     /// with the default. This means that we do not support indexing against a Geth node with
     /// `RPCGasCap` set below 25 million.
+    // See also f0af4ab0-6b7c-4b68-9141-5b79346a5f61.
```
Comment (otaviopace) [inline chain/ethereum/src/ethereum_adapter.rs:102]: Now I think it's missing one 😂
