### PR TITLE
fix: Allow grafts to add data sources

### LINKED ISSUE #3960: Adding data sources in graft not working
It's a reasonable use case for grafting to add a data source with a start block larger than the graft block. However the recent change to a private data sources table broke this, because it assumes that the manifest index of the templates is the same as in the source subgraph, and adding a data source will increase the manifest index. This can be fixed by translating the manifest indexes when grafting.

### PR DESCRIPTION
**Pull request by leoyvens**
Resolves #3960. This is done by adding a `raw_yaml` column to the `subgraph_manifest` table, and using it to map the manifest idx from the source to the destination deployment. For existing deployments this column is migrated in the instance manager on subgraph startup. This also changes a bit the order in which things are done in the instance manager, now the subgraph is first fetched from IPFS before being started in the store.

The `data-source-revert` integration test was modified to also test this.

### CODE REVIEW

File: graph/src/data/subgraph/schema.rs [hunk 1]
```diff
@@ -163,18 +164,52 @@ pub struct SubgraphManifestEntity {
...
             spec_version: manifest.spec_version.to_string(),
             description: manifest.description.clone(),
             repository: manifest.repository.clone(),
             features: manifest.features.iter().map(|f| f.to_string()).collect(),
             schema: manifest.schema.document.clone().to_string(),
+            raw_yaml: Some(raw_yaml),
         }
     }
+
+    pub fn template_idx_and_name(&self) -> Result<Vec<(i32, String)>, Error> {
```
Comment (neysofu) [inline graph/src/data/subgraph/schema.rs:182]: I understand we're using `i32` to simplify comparing these values with query results, but it would be nice to postpone the conversion and create a type alias for this tuple.

File: store/postgres/src/dynds/private.rs [hunk 2]
```diff
@@ -206,37 +207,80 @@ impl DataSourcesTable {
...
+                &self.manifest_idx,
+                &self.param,
+                &self.context,
+                &self.causality_region,
+            ))
+            .order_by(&self.vid)
+            .load::<Tuple>(conn)?;
+
+        let mut count = 0;
+        for (block_range, src_manifest_idx, param, context, causality_region) in src_tuples {
```
Comment (neysofu) [inline store/postgres/src/dynds/private.rs:242]: I suspect these N+1 queries may take longer than we'd like, but I don't have a better idea and N is most likely small for most subgraphs.

**Review by neysofu — APPROVED** [review]
LGTM, and nice small cleanups along the way! Just left two minor comments.

File: graph/src/util/error.rs [hunk 3]
```diff
@@ -17,3 +17,10 @@ macro_rules! ensure {
         }
     };
 }
+
+#[macro_export]
+macro_rules! bail {
+    ($($err:tt)*) => {
+        return Err(anyhow::anyhow!($($err)*).into());
+    };
+}
```
Comment (lutter) [inline graph/src/util/error.rs:26]: Why don't we just use the existing `anyhow::bail!` macro? If this is truly needed, maybe add a comment why.

File: graphql/tests/query.rs [hunk 4]
```diff
@@ -267,7 +267,7 @@ async fn insert_test_entities(
     manifest: SubgraphManifest<graph_chain_ethereum::Chain>,
     id_type: IdType,
 ) -> DeploymentLocator {
-    let deployment = DeploymentCreate::new(&manifest, None);
+    let deployment = DeploymentCreate::new(String::new(), &manifest, None);
```
Comment (lutter) [inline graphql/tests/query.rs:270]: Could we make the raw yaml an `Option` here? Alternatively, `deployment::set_manifest_raw_yaml` could translate an empty string back to `None`.

File: store/postgres/src/deployment.rs [hunk 5]
```diff
@@ -275,6 +276,21 @@ pub fn features(conn: &PgConnection, site: &Site) -> Result<BTreeSet<SubgraphFea
...
 
+/// This migrates subgraphs that existed before the raw_yaml column was added.
+pub fn set_manifest_raw_yaml(
+    conn: &PgConnection,
+    site: &Site,
+    raw_yaml: &str,
+) -> Result<(), StoreError> {
+    use subgraph_manifest as sm;
+
+    update(sm::table.filter(sm::id.eq(site.id)))
```
Comment (lutter) [inline store/postgres/src/deployment.rs:287]: It would be better to also include `.filter(sm::raw_yaml.ne(raw_yaml))` to avoid unnecessary updates in that table. Otherwise, we'd rewrite the entire table on each node start.

**Review by lutter — CHANGES_REQUESTED** [review]
The general approach looks good! Just some smaller detail comments on how we go about storing the raw yaml.

File: graph/src/util/error.rs (hunk 3 above)
Comment (leoyvens) [reply graph/src/util/error.rs:26]: It doesn't call `.into()`, yhea needs a comment.

File: graphql/tests/query.rs (hunk 4 above)
Comment (leoyvens) [reply graphql/tests/query.rs:270]: If the tests work, I would prefer not to make the interface more option-y just for the tests.

Comment (lutter) [reply graphql/tests/query.rs:270]: Oh, I totally missed that that was in the tests. Just ignore what I said.

**Review by lutter — APPROVED** [review]

File: store/postgres/src/deployment.rs (hunk 5 above)
Comment (lutter) [reply store/postgres/src/deployment.rs:287]: Sounds good! The sideeffect is that we'll never update the `raw_yaml` once it's set, but that shouldn't be an issue
