### PR TITLE
Add complete set of supported filters to graphql schema, squash several filter query building bugs

### LINKED ISSUE #222: Query interface not showing all where filters
Not all filters show up in the GraphiQL docs on the right sidebar, in addition the queries that are not shown trigger inline errors in the query interface though they do work when run.

### LINKED ISSUE #252: Using `ends_with` or `not_ends_with` filters causes panic
Panicked at: "internal error: entered unreachable code"

### PR DESCRIPTION
**Pull request by fordN**
Resolves #222 and Resolves #252 

The combined schema that was being generated only included a subset of the supported filter fields,`equals` and `not equals`, which was manifesting in inconsistent user experience; filters could be used in a query, but did not show up in the schema docs, and triggered inline errors in the query interface. During research and testing several other issues with the filter queries were revealed. 

Summary of updates made:
* Add complete set of where filters to schema for scalar fields. Each scalar type receives a specific set of filter fields
* Update tests to check for full list of filters
* Fix bugs in building filtered queries:
    * `postgres/src/filter` -  Filter match expression within EndsWith arm was trying to match against StartsWith
    * `graphql/src/schema/ast` - match arms in `parse_field_as_filter()` were not in correct order making several arms unreachable
    * `graph/src/data/store/mod` - `from_query_value()` was missing an arm for List filters on a NamedType schema

### CODE REVIEW

File: store/postgres/src/filter.rs [hunk 1]
```diff
@@ -317,8 +317,8 @@ fn store_filter_by_mode<'a>(
 
         StoreFilter::EndsWith(..) | StoreFilter::NotEndsWith(..) => {
             let (attribute, op, value) = match filter {
-                StoreFilter::StartsWith(attribute, value) => (attribute, " LIKE ", value),
-                StoreFilter::NotStartsWith(attribute, value) => (attribute, " NOT LIKE ", value),
+                StoreFilter::EndsWith(attribute, value) => (attribute, " LIKE ", value),
+                StoreFilter::NotEndsWith(attribute, value) => (attribute, " NOT LIKE ", value),
```
Comment (leodasvacas) [inline store/postgres/src/filter.rs]: Good catch, these new filters don't have unit tests, what do you think of taking the opportunity to add a test for an`EndsWith` query in `postgres/test/store.rs`?

File: graphql/src/schema/api.rs [hunk 2]
```diff
@@ -212,19 +212,39 @@ fn field_scalar_filter_input_values(
...
+            "ends_with",
+            "not_ends_with",
+        ],
+        _ => vec!["", "not"],
+    }.into_iter()
+        .map(|filter_type| {
+            input_value(
+                &field.name,
+                filter_type,
+                Type::NamedType(field_type.name.to_owned()),
```
Comment (leodasvacas) [inline graphql/src/schema/api.rs]: It seems that for `in` and `not_in` the correct type here would be `[Type]` (a list of `Type`) rather than just `Type`, so that in the docs we get for example `deposit_in: [BigInt]` rather than `deposit_in: BigInt` which is what currently appears.

File: graphql/src/schema/api.rs [hunk 3]
```diff
@@ -239,11 +239,13 @@ fn field_scalar_filter_input_values(
...
-            input_value(
-                &field.name,
-                filter_type,
-                Type::NamedType(field_type.name.to_owned()),
-            )
+            let value_type = match filter_type {
+                "in" | "not_in" => Type::ListType(Box::new(Type::NonNullType(Box::new(
+                    Type::NamedType(field_type.name.to_owned()),
+                )))),
+                _ => Type::NamedType(field_type.name.to_owned()),
```
Comment (leodasvacas) [inline graphql/src/schema/api.rs]: This code would look cleaner with `Type::NamedType(field_type.name.to_owned())` extracted to a variable.

File: graph/src/data/store/mod.rs [hunk 4]
```diff
@@ -1,7 +1,12 @@
 use graphql_parser::query;
 use graphql_parser::schema;
 
+use bigdecimal::BigDecimal;
+use diesel::pg::Pg;
```
Comment (Jannis) [inline graph/src/data/store/mod.rs]: I don't like seeing a dependency on Diesel in the `graph` crate. @leodasvacas @fordN I assume the only alternative would be to create `SqlValue(Value)` ad `SqlEntity(Entity)` newtypes in the `graph-store-postgres` crate and wrap entities in those before creating SQL statements?

File: graphql/src/schema/api.rs [hunk 5]
```diff
@@ -212,19 +212,42 @@ fn field_scalar_filter_input_values(
...
+            "ends_with",
+            "not_ends_with",
+        ],
+        _ => vec!["", "not"],
+    }.into_iter()
+        .map(|filter_type| {
+            let field_type = Type::NamedType(field_type.name.to_owned());
+            let value_type = match filter_type {
+                "in" | "not_in" => {
+                    Type::ListType(Box::new(Type::NonNullType(Box::new(field_type))))
```
Comment (Jannis) [inline graphql/src/schema/api.rs]: I _think_ there needs to be another `Type::NonNullType` around the `Type::ListType` to disallow `null` being passed in as a value (anything from an empty list upwards is fine, but `null` makes no sense).

File: graphql/src/schema/ast.rs [hunk 6]
```diff
@@ -25,14 +25,14 @@ pub(crate) fn parse_field_as_filter(key: &Name) -> (Name, FilterOp) {
         k if k.ends_with("_lt") => ("_lt", FilterOp::LessThan),
```
Comment (Jannis) [inline graphql/src/schema/ast.rs]: This file doesn't seem to have changed other than reordering the match branches. Is there a reason for changing the order?

File: store/postgres/src/filter.rs [hunk 7]
```diff
@@ -271,9 +271,72 @@ fn store_filter_by_mode<'a>(
         }
         // Is `attribute` equal to some `v` in `query_values`?
         StoreFilter::In(attribute, query_values) => {
-            query_values.into_iter().try_fold(query, |q, v| {
-                store_filter_by_mode(q, StoreFilter::Equal(attribute.clone(), v), FilterMode::Or)
-            })?
+            let op = " = ANY (";
+            match query_values[0].clone() {
```
Comment (Jannis) [inline store/postgres/src/filter.rs]: Is there anything that guarantees the list is not empty? Otherwise, this unconditional index access could panic.

File: store/postgres/src/filter.rs [hunk 8]
```diff
@@ -271,9 +271,72 @@ fn store_filter_by_mode<'a>(
...
+                Value::Bool(_) => add_filter(
```
Comment (Jannis) [inline store/postgres/src/filter.rs]: Do we have a task to track query validation? Unless we validate the values in the query, we'll have to assume that `query_values` could be a list with values of different types and then the `bind::<Array<Bool>, _>(query_values)` will trigger `unimplemented!()` and panic.

Comment (Jannis) [reply store/postgres/src/filter.rs]: An easy check we could perform upfront is whether all values have the same type (can be checked using a simple reduction over all values).

Can we create a task to do this and allow filter generation to fail and return an error back to the client in case it does?

File: store/postgres/src/store.rs [hunk 9]
```diff
@@ -236,6 +236,10 @@ impl BasicStore for Store {
                 .offset(range.skip as i64);
         }
 
+        {
+            debug!(self.logger, "find"; "Postgres query" => format!("{:?}", debug_query::<Pg, _>(&diesel_query)));
```
Comment (Jannis) [inline store/postgres/src/store.rs]: This line is too long. `rustfmt` can't properly format the semicolon syntax. Do it manually:
```rust
debug!(self.logger, "find";
       "sql" => format("{:?}", debug_query::<Pg, _>(&diesel_query)));
```
Also note that we're using single-word labels for keys in the logged key/value pairs ("sql" instead of "Postgres query").

File: graph/src/data/store/mod.rs (hunk 4 above)
Comment (leodasvacas) [reply graph/src/data/store/mod.rs]: That's the only alternative I see. I think it's ok for `graph` to take the dependency, but ideally we'd re-export  diesel from `graph` and then `graph-store-postgres` would not depend directly on diesel, so we can control the diesel version and features from a single `Cargo.toml`. This is what was done for `slog` and `tokio`.

File: graph/src/data/store/mod.rs [hunk 10]
```diff
@@ -114,6 +119,55 @@ impl<'a> From<&'a String> for Value {
     }
 }
 
+impl ToSql<Bool, Pg> for Value {
+    fn to_sql<W: Write>(&self, out: &mut Output<W, Pg>) -> serialize::Result {
+        match *self {
+            Value::Bool(ref b) => <bool as ToSql<Bool, Pg>>::to_sql(&b, out),
+            _ => unimplemented!(),
```
Comment (leodasvacas) [inline graph/src/data/store/mod.rs]: `unimplemented` isn't the right description here, a custom panic message would be better.

File: graphql/src/schema/ast.rs (hunk 6 above)
Comment (fordN) [reply graphql/src/schema/ast.rs]: The order is important here because some of the arms' match strings are contained in others, so the previous order created essentially unreachable arms.  Example: if the .ends_with("_in") arm comes before .ends_with("_not_in") the "_not_in" arm will never be matched because "_not_in" ends_with "_in".         

For this reason I made sure:
-  "_not_starts_with" comes before "_starts_with"
-  "_not_ends_with" comes before "_ends_with" 
- "_in" comes before "_not_in"
-  "_contains" comes before "_not_contains".

Comment (Jannis) [reply graphql/src/schema/ast.rs]: Oh, _of course_! Thanks for explaining, I should've seen that...

File: graph/src/data/store/mod.rs (hunk 4 above)
Comment (Jannis) [reply graph/src/data/store/mod.rs]: That's ok but we will very likely replace Postgres at some point and to avoid making that too hard, depending on it anywhere else but in `store/postgres` is a bad idea.

File: store/postgres/src/filter.rs (hunk 8 above)
Comment (fordN) [reply store/postgres/src/filter.rs]: I created issue #272 to track validation of `query_values`.

File: store/postgres/src/filter.rs (hunk 7 above)
Comment (fordN) [reply store/postgres/src/filter.rs]: This will also be resolved by issue #272.

File: store/postgres/src/filter.rs [hunk 11]
```diff
@@ -271,9 +271,72 @@ fn store_filter_by_mode<'a>(
         }
         // Is `attribute` equal to some `v` in `query_values`?
         StoreFilter::In(attribute, query_values) => {
-            query_values.into_iter().try_fold(query, |q, v| {
-                store_filter_by_mode(q, StoreFilter::Equal(attribute.clone(), v), FilterMode::Or)
-            })?
+            let op = " = ANY (";
```
Comment (leodasvacas) [inline store/postgres/src/filter.rs]: Diesel query builder has support for this https://docs.diesel.rs/diesel/expression_methods/trait.ExpressionMethods.html#method.eq_any, I wonder if we can use it here.

File: store/postgres/src/models.rs [hunk 12]
```diff
@@ -17,3 +23,61 @@ pub struct EntityTable {
...
+    pub fn new_array(values: Vec<Value>) -> Vec<Self> {
+        values.into_iter().map(|value| SqlValue(value)).collect()
+    }
+}
+
+impl ToSql<Bool, Pg> for SqlValue {
+    fn to_sql<W: Write>(&self, out: &mut Output<W, Pg>) -> serialize::Result {
+        match self.0 {
+            Value::Bool(ref b) => <bool as ToSql<Bool, Pg>>::to_sql(&b, out),
+            _ => unimplemented!(),
```
Comment (leodasvacas) [inline store/postgres/src/models.rs]: `unimplemented` isn't the right description here, a custom panic message would be better.

File: store/postgres/src/filter.rs (hunk 11 above)
Comment (fordN) [reply store/postgres/src/filter.rs]: I don't see a reasonable way through using diesel expression methods like `eq_any()` with our`jsonb` attributes right now.  

We could create a custom type that uses diesel-dynamic-schema to build the structs at runtime, but I think that would also require looking at the schema to see what attributes are on each entity.

File: store/postgres/src/models.rs [hunk 13]
```diff
@@ -17,3 +23,61 @@ pub struct EntityTable {
...
+    pub fn new_array(values: Vec<Value>) -> Vec<Self> {
+        values.into_iter().map(|value| SqlValue(value)).collect()
+    }
+}
+
+impl ToSql<Bool, Pg> for SqlValue {
+    fn to_sql<W: Write>(&self, out: &mut Output<W, Pg>) -> serialize::Result {
+        match self.0 {
+            Value::Bool(ref b) => <bool as ToSql<Bool, Pg>>::to_sql(&b, out),
+            _ => panic!("Invalid input type, all items in array must be Bool"),
```
Comment (Jannis) [inline store/postgres/src/models.rs]: `ToSql<Bool, Pg>` has nothing to do with arrays, so this message is confusing (same with the messages below). How about: "failed to convert non-boolean attribute value to boolean in SQL"?

File: store/postgres/src/store.rs [hunk 14]
```diff
@@ -233,6 +233,11 @@ impl BasicStore for Store {
                 .offset(range.skip as i64);
         }
 
+        {
+            debug!(self.logger, "find";
+                "sql" => format!("{:?}", debug_query::<Pg, _>(&diesel_query)));
```
Comment (Jannis) [inline store/postgres/src/store.rs]: The alignment here is off by a few spaces. I'm also not sure why we need a dedicated scope around the `debug!` statement.

File: store/postgres/src/store.rs [hunk 15]
```diff
@@ -233,9 +233,10 @@ impl BasicStore for Store {
                 .offset(range.skip as i64);
         }
 
-        {
-            debug!(self.logger, "find"; "Postgres query" => format!("{:?}", debug_query::<Pg, _>(&diesel_query)));
-        }
+
+        debug!(self.logger, "find";
+            "sql" => format!("{:?}", debug_query::<Pg, _>(&diesel_query)));
```
Comment (fordN) [inline store/postgres/src/store.rs]: I'm not clear on how the alignment is off here?  I'm using a single indent on the second line.

Comment (Jannis) [reply store/postgres/src/store.rs]:
```
        debug!(self.logger, "find";
            "sql" => format!("{:?}", debug_query::<Pg, _>(&diesel_query)));
```
vs.
```
        debug!(self.logger, "find";
               "sql" => format!("{:?}", debug_query::<Pg, _>(&diesel_query)));
```
which one is aligned correctly?

Comment (fordN) [reply store/postgres/src/store.rs]: nm. I see how it needs to be formatted.
