### PR TITLE
store: Fix fulltextsearch space handling

### LINKED ISSUE #3043: Fulltext search queries with spaces (but no operators) fail badly
On https://thegraph.com/hosted-service/subgraph/graphprotocol/everest, the following query fails pretty badly:

```graphql
{
  projectSearch(text:"using graphql") {
    name
  }
}
```

The error is:

```json
{
  "errors": [
    {
      "message": "Failed to get entities from store: syntax error in tsquery: \"using graphql\", query = \"/* qid: 5ff630b7821b817d-7bb418afea0e1b23 */\\nselect 'Project' as entity, c.vid, to_jsonb(c.*) as data from (select  * \\n  from \\\"sgd16672\\\".\\\"project\\\" c\\n where c.\\\"block_range\\\" @> $1 and \\\"project_search\\\" @@ to_tsquery($2)\\n\\n order by ts_rank(\\\"project_search\\\", to_tsquery($3)) asc, \\\"id\\\" asc\\n limit 100) c -- binds: [13764251, \\\"using graphql\\\", \\\"using graphql\\\"]\""
    }
  ]
}
```

1. This should probably work?
2. If it is expected to fail, the error certainly reveals way too many details about database internals.

### PR DESCRIPTION
**Pull request by mangas**
Fixes #3043

### CODE REVIEW

File: store/postgres/src/relational_queries.rs [hunk 1]
```diff
@@ -529,7 +529,11 @@ impl<'a> QueryFragment<Pg> for QueryValue<'a> {
                 }
                 ColumnType::TSVector(_) => {
                     out.push_sql("to_tsquery(");
-                    out.push_bind_param::<Text, _>(s)?;
+                    let mut value = s.clone();
```
Comment (lutter) [inline store/postgres/src/relational_queries.rs:532]: I don't think that clone is needed.

File: store/postgres/src/relational_queries.rs [hunk 2]
```diff
@@ -529,7 +529,11 @@ impl<'a> QueryFragment<Pg> for QueryValue<'a> {
...
+                    if value.contains(" ") {
+                        value = format!("'{}'", value);
+                    }
+                    out.push_bind_param::<Text, _>(&value)?;
```
Comment (lutter) [inline store/postgres/src/relational_queries.rs:536]: In this code, we try to avoid allocations as much as possible since diesel will call this code 3 or 4 times every time we issue a query, even though in this case it can't be avoided entirely. It would be better to structure this as
```rust
if s.contains(" ") {
  out.push_bind_param::<Text,_>(&format!("'{}'}, s)?;
} else {
  out.push_bind_param::<Text, _>(&s)?;
}
```

Also, is containing a space the only reason why this needs to be quoted? What happens if the value contains single quotes like `"John O'Leary"`?

File: store/postgres/src/relational_queries.rs [hunk 3]
```diff
@@ -2182,7 +2186,11 @@ impl<'a> SortKey<'a> {
                 out.push_identifier(name)?;
                 out.push_sql(", to_tsquery(");
 
-                out.push_bind_param::<Text, _>(&value.unwrap())?;
+                let mut value = value.unwrap().to_string();
+                if value.contains(" ") {
+                    value = format!("'{}'", value);
+                }
+                out.push_bind_param::<Text, _>(&value.as_str())?;
```
Comment (lutter) [inline store/postgres/src/relational_queries.rs:2193]: Since the exact same code is used twice, it would be better to factor that into a helper `fn to_tsquery(value: &str, out: &mut AstPass<Pg>) -> QueryResult<()> { .. }`

File: store/postgres/tests/relational.rs [hunk 4]
```diff
@@ -1000,6 +1000,10 @@ fn check_find() {
                 vec!["3"],
                 user_query().filter(EntityFilter::Equal("userSearch".into(), "Shaq:*".into())),
             )
+            .check(
+                vec!["1"],
+                user_query().filter(EntityFilter::Equal("userSearch".into(), "Jono a".into())),
+            )
```
Comment (lutter) [inline store/postgres/tests/relational.rs:1006]: Yes, I think this is exactly the right kind of test (I assume it was failing before the changes above)

We should try and see if there are other funky search terms that cause `to_tsquery` to fail. It's probably also worth checking with @fordN who wrote this initially because IIRC it is possible to put some of the text search operators into the search string.

File: store/postgres/src/relational_queries.rs (hunk 2 above)
Comment (mangas) [reply store/postgres/src/relational_queries.rs:536]: I'll add a test, we probably need to escape any additional single quotes before pushing it

File: store/postgres/src/relational_queries.rs (hunk 3 above)
Comment (mangas) [reply store/postgres/src/relational_queries.rs:2193]: there are a few more edges like the List case which does a similar thing, I was thinking that this needs a little more work. I was wondering if it would be worth adding something like a quote fn for handling this in all the places as well as add the tests.

File: store/postgres/tests/relational.rs (hunk 4 above)
Comment (mangas) [reply store/postgres/tests/relational.rs:1006]: cool, will do. There are definitely a few more use cases as well

Comment (mangas) [reply store/postgres/tests/relational.rs:1006]: And yep it was failing before the code changes :)

File: graph/src/data/query/error.rs [hunk 5]
```diff
@@ -273,6 +275,7 @@ impl fmt::Display for QueryExecutionError {
             Panic(msg) => write!(f, "panic processing query: {}", msg),
             EventStreamError => write!(f, "error in the subscription event stream"),
             FulltextQueryRequiresFilter => write!(f, "fulltext search queries can only use EntityFilter::Equal"),
+            FulltextQueryInvalidSyntax(msg) => write!(f, "Invalid fulltext search query syntax. msg: {}. Tip: Spaces are only allowed around operators", msg),
```
Comment (Jannis) [inline graph/src/data/query/error.rs:278]: I would leave out the `msg: {}.` part because that's the cryptic in-db details that we probably shouldn't expose to the client (database schema names etc.).

**Review by Jannis — CHANGES_REQUESTED** [review]

File: graph/src/data/query/error.rs (hunk 5 above)
Comment (Jannis) [reply graph/src/data/query/error.rs:278]: Change to `Invalid fulltext search query syntax. Error: {}. Hint: Search terms with spaces need to be put in single quotes`?

Comment (mangas) [reply graph/src/data/query/error.rs]: updated

**Review by Jannis — APPROVED** [review]
LGTM!

**Review by Jannis — APPROVED** [review]

**Review by leoyvens — APPROVED** [review]
Didn't know you could have an expected message in `should_panic`, nice!
