### PR TITLE
Don't fail when no matching event handlers are found (#1021)

### LINKED ISSUE #1021: Graph processing should not fail when no matching handlers are found
The new support for trying multiple handlers is excellent, but graph processing still fails if at least one handler matches `topics[0]`, but none of them can successfully decode the event data.

This makes graphs that subscribe to events from multiple addresses still vulnerable to disruption. Instead, a warning should be logged and graph processing should continue.

### PR DESCRIPTION
**Pull request by Jannis**
Instead, just log a warning and skip processing the event.

Fixes #1021.

### CODE REVIEW

**Review by ghost — APPROVED** [review]

File: runtime/wasm/src/host.rs [hunk 1]
```diff
@@ -774,17 +774,20 @@ impl RuntimeHostTrait for RuntimeHost {
             })
             .collect::<Vec<_>>();
 
-        // If none of the handlers match the event params, fail processing the event
+        // If none of the handlers match the event params, log a warning and
+        // skip the event. See https://github.com/graphprotocol/graph-node/issues/1021
```
Comment (leodasvacas) [inline runtime/wasm/src/host.rs]: I'm fine with referencing issues with just `#1021` if you also prefer that.

Comment (Jannis) [reply runtime/wasm/src/host.rs]: I am :)
