### PR TITLE
Refactor index creation and fix unncessary prefix

### LINKED ISSUE #4982: [Bug] `graphman index create` indexes prefixes when it shouldn't
### Bug report

The command `graphman index create` indexes prefixes of columns in some cases (e.g., when indexing `id` it creates and index on `left(id,..)`) when the whole column should be indexed. The problem is that `deployment_store::resolve_index_exprs` indexes prefixes for all `String` and `Bytes` columns when it should use the entire column if the column is a reference. 

The logic in `resolve_index_exprs` needs to match the logic [here](https://github.com/graphprotocol/graph-node/blob/master/store/postgres/src/relational/ddl.rs#L228-L270) It would probably be cleanest to factor this logic into a helper and use it in both places, not sure how complicated that will be. 

### Relevant log output

_No response_

### IPFS hash

_No response_

### Subgraph name or link to explorer

_No response_

### Some information to help us out

- [X] Tick this box if this bug is caused by a regression found in the latest release.
- [ ] Tick this box if this bug is specific to the hosted service.
- [X] I have searched the issue tracker to make sure this issue is not a duplicate.

### OS information

None

### PR DESCRIPTION
**Pull request by incrypto32**
Closes #4982

### CODE REVIEW

File: store/postgres/src/relational/ddl.rs [hunk 1]
```diff
@@ -198,6 +198,56 @@ impl Table {
...
+    /// * `column`: A reference to the `Column` struct, representing the database column for which the index method and expression are being calculated.
+    ///
+    /// ### Returns
+    /// A tuple `(String, String)` where:
+    /// - The first element is the indexing method ("btree", "gist", or "gin"),
+    /// - The second element is the index expression as a string.
+    pub fn calculate_index_method_and_expression(
+        immutable: bool,
+        column: &Column,
+    ) -> (String, String) {
```
Comment (lutter) [inline store/postgres/src/relational/ddl.rs:214]: There's an enum for index methods [here](https://github.com/graphprotocol/graph-node/blob/master/store/postgres/src/relational/index.rs#L17) - it would be better to use that. I wonder if that should return the whole `CreateIndex` from that file instead of the second string, but that might become a bit too unwieldy. Maybe some or all of this logic should go into a new constructor for `CreateIndex`

Comment (lutter) [reply store/postgres/src/relational/ddl.rs:214]: Actually, I think what I said above would be good for another refactor, but what you have here is ok for now.

**Review by lutter — APPROVED** [review]
