### PR TITLE
Validate field exists in schema before setting entity

### LINKED ISSUE #4791: [Bug] Validate entities before creating Proof of Indexing
### Bug report

When investigating a POI divergence between two graph-node versions, a polygon subgraph `QmWTuqjkyGogHMBuGvQHZjkb189CN4EtGi8ps1yT76Vj9V` diverges at block `45504938`, On further investigation by checking logs the only difference found was a `Proof of Indexing` event log 

Screenshot 2023-08-04 at 9 05 05 PM

The `HourlyVolumeBySource` does not have  a field named `marginAndLiquidation` but still that field is being set to 0 in this case.

Here is the [schema](https://api.thegraph.com/ipfs/api/v0/cat?arg=QmfBAQwYcabyiQ9BH5txv8yQiMnBR9V7bba1nLyXRqiRqt) of this subgraph. There is another entity `FeeStat` which has `marginAndLiquidation` entity

### Relevant log output

_No response_

### IPFS hash

QmWTuqjkyGogHMBuGvQHZjkb189CN4EtGi8ps1yT76Vj9V

### Subgraph name or link to explorer

_No response_

### Some information to help us out

- [ ] Tick this box if this bug is caused by a regression found in the latest release.
- [ ] Tick this box if this bug is specific to the hosted service.
- [X] I have searched the issue tracker to make sure this issue is not a duplicate.

### OS information

None

### PR DESCRIPTION
**Pull request by incrypto32**
Closes #4791 #4466

### CODE REVIEW

**Review by lutter — APPROVED** [review]

File: graph/src/data/store/mod.rs [hunk 1]
```diff
@@ -846,6 +847,31 @@ impl Entity {
             }
         }
 
+        fn validate_fields<'a>(
```
Comment (mangas) [inline graph/src/data/store/mod.rs:850]: IMO this name is ambiguous, would prefer something like check_missing_fields or validate_missing_fields, since it's all it does and this way you can easily glean this information from the name

File: graph/src/data/store/mod.rs [hunk 2]
```diff
@@ -846,6 +847,31 @@ impl Entity {
...
+            field_names_iter: impl Iterator<Item = &'a str>,
+            object_type: &ObjectType<'_, String>,
+        ) -> Result<(), Error> {
+            let fields_set: HashSet<_> =
+                object_type.fields.iter().map(|f| f.name.as_str()).collect();
```
Comment (mangas) [inline graph/src/data/store/mod.rs:855]: I think this might be overkill for most entities which are probably small (a bit arbitrary) but this function seems to be called potentially twice per `set` operation on the entity cache . I think it may be better to either consider storing the fields on a hashset to begin with at the entity level, or ensure they are ordered by name and just lookup on the vec which *should* be a lot cheaper for smaller entities.

Comment (mangas) [reply graph/src/data/store/mod.rs:855]: cc @lutter for an opinion

File: runtime/test/src/test.rs [hunk 3]
```diff
@@ -1389,3 +1390,143 @@ async fn test_store_set_id() {
...
+    let err = host
+        .store_set(
+            USER,
+            UID,
+            vec![("id", "u1"), ("name", "user1"), ("test3", "invalid_field")],
+        )
+        .err()
+        .unwrap();
+
+    err_says(
```
Comment (mangas) [inline runtime/test/src/test.rs:1528]: Could be worth creating a ValidationError with the current anonymous errors and check on types if you feel up for that

File: graph/src/data/store/mod.rs [hunk 4]
```diff
@@ -846,6 +847,31 @@ impl Entity {
...
+
+            // Fields that are not in `object_type.fields`
+            let missing_fields: Vec<_> = field_names_iter
```
[the remark this answers is not in the document]
Comment (incrypto32) [reply graph/src/data/store/mod.rs:858]: We are failing anyways. So why not fail with a better error message? 
If there are no missing fields we would have to iterate through the entire thing anyways.

File: graph/src/data/store/mod.rs (hunk 1 above)
Comment (incrypto32) [reply graph/src/data/store/mod.rs:850]: thanks will make that change

File: graph/src/data/store/mod.rs (hunk 2 above)
Comment (mangas) [reply graph/src/data/store/mod.rs:855]: it may be a more complicated change but possibly sorting entries in the Object from intern.rs could be useful for this since we could have `field_names_iter` sorted which means that looking up is amortized and probably cheaper than creating a HashSet + a Vec for each validation

Comment (mangas) [reply graph/src/data/store/mod.rs:855]: nitpick: The naming here could also be improved. Something like `set_fields(_iter)` instead of `field_names_iter` and `object_schema` rather than `object_type`would feel a bit easier IMO but obviously it's subjective and nitpicky

File: graph/src/data/store/mod.rs (hunk 4 above)
[the remark this answers is not in the document]
Comment (mangas) [reply graph/src/data/store/mod.rs:858]: That's a good point 👍

**Comment by incrypto32** [comment]
Refactored the test a bit to avoid code duplication for the implementation of the mocked `Host`

File: graph/src/data/store/mod.rs (hunk 2 above)
Comment (lutter) [reply graph/src/data/store/mod.rs:854]: I am not sure how much of an issue this will be in the end, but I am also a little concerned about the impact of creating a `HashSet` all the time .. I think using `.contains()` will be preferable since object types generally have a small number of fields and so its likely that a quadratic algorithm here won't hurt much.

Another option would be to precompute the `HashSet` when the `InputSchema` is created, store them in a map `type name -> HashSet` and use those for this check.

A third option is to store a `Vec` of atoms for each object type in the `InputSchema` and compare against that - since you are only comparing integers at that point, and the `Vec` will fit into a cache line in almost all cases, that's probably the fastest way to do that.

Comment (incrypto32) [reply graph/src/data/store/mod.rs:854]: How would option 3 work @lutter?
add a new Map<ObjectType, Atom> and store the Atom corresponding to the fields.
Then wouldn't we need to look up the Atom from the pool first with the `field_name` only then we could compare right? 

I'd go with 1 for now and make the changes to use the `.contains()` let me know if 3 would be worth it. I'll do that if so.

File: graph/src/data/store/mod.rs [hunk 5]
```diff
@@ -647,6 +649,38 @@ pub trait TryIntoEntityIterator<E>: IntoIterator<Item = Result<(Word, Value), E>
 
 impl<E, T: IntoIterator<Item = Result<(Word, Value), E>>> TryIntoEntityIterator<E> for T {}
 
+#[derive(Debug, Error, PartialEq, Eq)]
+pub enum EntityValidationError {
```
Comment (incrypto32) [inline graph/src/data/store/mod.rs:653]: @mangas I added new `EntityValidationError` enum and migrated all the validation error to use it.

File: graph/src/data/store/mod.rs [hunk 6]
```diff
@@ -647,6 +649,38 @@ pub trait TryIntoEntityIterator<E>: IntoIterator<Item = Result<(Word, Value), E>
...
+    #[error("The provided entity has fields not defined in the schema for entity `{0}`: {1}")]
+    FieldsNotDefined(String, String),
```
Comment (mangas) [inline graph/src/data/store/mod.rs:655]: in most of these, I feel like having named fields would be a lot better, 

```
    #[error(
        "The provided entity has fields not defined in the schema for entity `{entity}`: {field}"
    )]
    FieldsNotDefined { entity: String, field: String },

```

File: graph/src/data/store/mod.rs [hunk 7]
```diff
@@ -647,6 +649,38 @@ pub trait TryIntoEntityIterator<E>: IntoIterator<Item = Result<(Word, Value), E>
...
+    #[error("Entity {0}[{1}]: unknown entity type `{0}`")]
+    UnknownEntityType(String, String),
+
+    #[error("Entity {0}[{1}]: field `{2}` is of type {3}, but the value `{4}` contains a {5} at index {6}")]
+    MismatchedElementTypeInList(String, String, String, String, String, String, usize),
+
+    #[error(
+        "Entity {0}[{1}]: the value `{2}` for field `{3}` must have type {4} but has type {5}"
+    )]
+    InvalidFieldType(String, String, String, String, String, String),
```
Comment (mangas) [inline graph/src/data/store/mod.rs:666]: especially this one xD

File: runtime/test/src/test.rs (hunk 3 above)
Comment (mangas) [reply runtime/test/src/test.rs:1454]: Here you should now be able to check the error returned rather than the message error, this is why the enum is useful

File: store/postgres/src/fork.rs [hunk 8]
```diff
@@ -220,7 +221,11 @@ query Query ($id: String) {{
             map
         };
 
-        Ok(Some(schema.make_entity(map)?))
+        Ok(Some(
+            schema
+                .make_entity(map)
+                .map_err(|e| StoreError::Unknown(anyhow!(e)))?,
```
Comment (mangas) [inline store/postgres/src/fork.rs:227]: I think it's probably worth adding something like an EntityValidationError value 

something along the lines of 

#[error("Entity validation failed: {0}")}
EntityValidationError(#[from] graph::whatever::EntityValidationError)

Comment (mangas) [reply store/postgres/src/fork.rs:227]: since we do know what kind of error it is in this case

File: graph/src/data/store/mod.rs (hunk 7 above)
Comment (incrypto32) [reply graph/src/data/store/mod.rs:666]: Thanks for catching those, I was blindly following how error struct from other parts of the [code](https://github.com/graphprotocol/graph-node/blob/48e0958e505b95a0d59ee6b3ef3d874cacda97eb/graph/src/schema/mod.rs#L69).

But this one clearly needs to be named. Thanks will keep an eye for such things going forward

File: runtime/test/src/test.rs (hunk 3 above)
Comment (incrypto32) [reply runtime/test/src/test.rs:1454]: The problem is its no longer `EntityValidationError` anymore it get anonymised in between an only the message gets passed into `HostExportError:Deterministic`

Comment (mangas) [reply runtime/test/src/test.rs:1454]: 🤦‍♂️ okay, oh well

File: store/postgres/src/fork.rs (hunk 8 above)
Comment (incrypto32) [reply store/postgres/src/fork.rs]: changed

File: graph/src/data/store/mod.rs (hunk 2 above)
Comment (lutter) [reply graph/src/data/store/mod.rs]: yeah, I think going with (1) will be fine for now; what I had in mind for (3) was a `Map<ObjectType, Vec<Atom>>` where the `Vec<Atom>` contains all the field names for the object type.

Comment (lutter) [reply graph/src/data/store/mod.rs]: One other small complication: the object type will also have the names of derived fields, even though they can't be set directly. Maybe we should precompute that map for (3) and only include non-derived fields for each type.

**Comment by incrypto32** [comment]
Rebased with master

**Review by mangas — APPROVED** [review]
