### PR TITLE
Handle Ethereum Firehose decoding issues without crashing

### LINKED ISSUE #3460: ETH Firehose: Avoid crash when Firehose block stream data is invalid
Currently, graph-node crashes completely when encountering invalid `EthereumCallData` from a Firehose block stream. This should only fail the subgraph in question but not take down the entire node.

```rust
Apr 13 08:01:25.112 DEBG trigger data: TriggerWithHandler { trigger: Log { _transaction: Transaction { hash: 0x15ec3ceb9e68bfb80808e766e9a38168308083a1adb92c2f286227b53548d086, nonce: 762, block_hash: Some(0xd79c9f0aaf36d287049349b977866ecdb629a5967628c64a39836008f1829b0c), block_number: Some(14263684), transaction_index: Some(168), from: Some(0x50453363ed21240ead1a7dc1cc2ca1e09399f21d), to: Some(0x0000000035634b55f3d99b071b5a354f48e10bef), value: 1371600000000000000, gas_price: Some(120000000000), gas: 351898, input: Bytes([105, 185, 201, 142, 141, 113, 92, 37, 179, 48, 208, 212, 235, 7, 230, 140, 187, 127, 108, 252, 3, 172, 98, 22, 111, 80, 18, 243, 171, 131, 12, 221, 157, 179, 72, 160, 106, 142, 218, 6, 25, 169, 194, 236, 16, 184, 27, 110, 3, 143, 140, 107, 27, 192, 67, 27, 122, 172, 58, 26, 201, 56, 66, 88, 52, 124, 128, 115, 19, 175, 106, 200, 132, 152, 162, 65, 198, 231, 227, 109, 173, 210, 71, 201, 18, 14, 53, 13, 33, 140, 178, 119, 35, 186, 118, 152, 48, 27, 244, 32, 240, 169, 108, 128, 181, 183, 48, 108, 128, 113, 50, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 32, 231, 98, 23, 168, 178, 10, 74, 45, 94, 213, 0, 210, 32, 204, 61, 196, 205, 181, 132, 8, 235, 31, 140, 57, 3, 215, 145, 99, 137, 167, 58, 0, 162, 170, 8, 117, 34, 0, 0, 0, 9, 129, 155, 222, 231, 36, 128, 0, 98, 22, 110, 126, 127, 156, 51, 216, 209, 180, 166, 201, 100, 211, 184, 85, 171, 96, 195, 78, 191, 97, 142, 18, 27, 146, 191, 111, 20, 189, 11, 190, 32, 130, 249, 143, 161, 188, 197, 199, 137, 38, 48, 144, 187, 168, 223, 182, 80, 149, 60, 34, 251, 115, 198, 60, 195, 11, 51, 122, 111, 141, 114, 2, 12, 234, 148, 49, 160, 243, 98, 158, 162, 117, 33, 231, 168, 58, 250, 138, 180, 218, 244, 14, 135, 211, 130, 123, 174, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 31, 44, 98, 22, 121, 107, 128, 202, 147, 232, 47, 20, 225, 215, 235, 167, 54, 250, 109, 211, 147, 152, 87, 76, 199, 129, 113, 54, 180, 124, 205, 46, 232, 221, 112, 201, 115, 245, 0, 0, 0, 9, 135, 75, 15, 238, 200, 128, 0]), v: None, r: None, s: None, raw: None, transaction_type: None, access_list: None, max_fee_per_gas: None, max_priority_fee_per_gas: None }, _log: Log { address: 0x69b9c98e8d715c25b330d0d4eb07e68cbb7f6cfc, topics: [0xddf252ad1be2c89b69c2b068fc378daa952ba7f163c4a11628f55a4df523b3ef, 0x00000000000000000000000012f3ab830cdd9db348a06a8eda0619a9c2ec10b8, 0x00000000000000000000000050453363ed21240ead1a7dc1cc2ca1e09399f21d, 0x00000000000000000000000000000000000000000000000000000000000020e7], data: Bytes([]), block_hash: Some(0xd79c9f0aaf36d287049349b977866ecdb629a5967628c64a39836008f1829b0c), block_number: Some(14263684), transaction_hash: Some(0x15ec3ceb9e68bfb80808e766e9a38168308083a1adb92c2f286227b53548d086), transaction_index: Some(168), log_index: Some(137), transaction_log_index: Some(1), log_type: None, removed: None }, _params: [LogParam { name: "from", value: Address(0x12f3ab830cdd9db348a06a8eda0619a9c2ec10b8) }, LogParam { name: "to", value: Address(0x50453363ed21240ead1a7dc1cc2ca1e09399f21d) }, LogParam { name: "tokenId", value: Uint(8423) }] }, handler: "handleTransfer" }, sgd: 156, subgraph_id: QmTSfzM6SpdasWr1Zus3ZaAsKyzj5RfDJod9SPBwTLHyB3, component: SubgraphInstanceManager
thread 'tokio-runtime-worker' panicked at 'assertion failed: `(left == right)`
  left: `0`,
 right: `20`', /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/primitive-types-0.11.1/src/lib.rs:55:1
stack backtrace:
   0: rust_begin_unwind
   1: core::panicking::panic_fmt
   2: core::panicking::assert_failed_inner
   3: core::panicking::assert_failed
   4: primitive_types::H160::from_slice
   5: <graph_chain_ethereum::codec::CallAt as core::convert::Into<graph::components::ethereum::types::EthereumCall>>::into
   6: core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &mut F>::call_once
   7: <core::iter::adapters::flatten::FlatMap<I,U,F> as core::iter::traits::iterator::Iterator>::next
   8: <alloc::vec::Vec<T> as alloc::vec::spec_from_iter::SpecFromIter<T,I>>::from_iter
   9: graph_chain_ethereum::codec::<impl core::convert::Into<graph::components::ethereum::types::EthereumBlockWithCalls> for &graph_chain_ethereum::codec::pbcodec::Block>::into
  10: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
  11: graph::blockchain::firehose_block_stream::stream_blocks::{{closure}}
  12: <async_stream::async_stream::AsyncStream<T,U> as futures_core::stream::Stream>::poll_next
  13: <graph::blockchain::firehose_block_stream::FirehoseBlockStream<C> as futures_core::stream::Stream>::poll_next
  14: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
  15: <futures_util::future::future::map::Map<Fut,F> as core::future::future::Future>::poll
  16: std::panicking::try
  17: tokio::runtime::task::harness::poll_future
  18: tokio::runtime::task::harness::Harness<T,S>::poll
  19: std::thread::local::LocalKey<T>::with
  20: tokio::runtime::thread_pool::worker::Context::run_task
  21: tokio::runtime::thread_pool::worker::Context::run
  22: tokio::macros::scoped_tls::ScopedKey<T>::set
  23: tokio::runtime::thread_pool::worker::run
  24: <tokio::runtime::blocking::task::BlockingTask<T> as core::future::future::Future>::poll
  25: tokio::runtime::task::harness::Harness<T,S>::poll
  26: tokio::runtime::blocking::pool::Inner::run
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
Panic in tokio task, aborting!
```

### PR DESCRIPTION
**Pull request by Jannis**
This fixes #3460 by using `TryFrom` when decoding Ethereum Firehose blocks and then handling the error by retrying the same block over and over again (with exponential back-off). Before, graph-node would crash completely.

### CODE REVIEW

File: graph/src/blockchain/firehose_block_stream.rs [hunk 1]
```diff
@@ -215,6 +211,13 @@ fn stream_blocks<C: Blockchain, F: FirehoseMapper<C>>(
         debug!(&logger, "Going to check continuity of chain on first block");
     }
 
+    // Back off exponentially whenever we encounter a connection error or a stream with bad data
+    let mut backoff = ExponentialBackoff::new(Duration::from_millis(500), Duration::from_secs(45));
+
+    // This macro is needed because `try_stream!` seems to break detection of `skip_backoff` assignments
```
Comment (leoyvens) [inline graph/src/blockchain/firehose_block_stream.rs:217]:
```suggestion
    // This attribute is needed because `try_stream!` seems to break detection of `skip_backoff` assignments
```

**Review by leoyvens — APPROVED** [review]
