### PR TITLE
Graphman deploy command

### LINKED ISSUE #4842: [Feature] Add a `graphman deploy`
### Description

It is sometimes useful to make a deployment available under a different name. Administrators should be able to do this by running `graphman deploy [--create] <name> <ipfs hash>`

If the `--create` flag is passed, the command should fail when `name` already exists, and create a new name and deploy to it if it does not.

### Are you aware of any blockers that must be resolved before implementing this feature? If so, which? Link to any relevant GitHub issues.

_No response_

### Some information to help us out

- [ ] Tick this box if you plan on implementing this feature yourself.
- [X] I have searched the issue tracker to make sure this issue is not a duplicate.

### PR DESCRIPTION
**Pull request by incrypto32**
Closes #4842

### CODE REVIEW

File: node/src/bin/manager.rs [hunk 1]
```diff
@@ -344,6 +344,20 @@ pub enum Command {
...
     },
+
+    // Deploy a subgraph
+    Deploy {
+        name: DeploymentSearch,
+        deployment: DeploymentSearch,
+
+        /// The url of the graph-node
+        #[clap(long, short, default_value = "http://localhost:8020")]
+        url: String,
```
Comment (lutter) [inline node/src/bin/manager.rs:355]: It would be awesome if we would _not_ need a `url`, but getting away from that might be pretty tough as we would have to instantiate our own `SubgraphRegistrar`; if the default is ok in most cases, I think it's not a big deal.

File: node/src/manager/commands/deploy.rs [hunk 2]
```diff
@@ -0,0 +1,101 @@
...
+            }
+
+            // Send the subgraph_deploy request
+            println!("Deploying subgraph `{}` to `{}`", hash, name);
+            send_deploy_request(&name, &hash, &url).await?;
+            println!("Subgraph `{}` deployed to `{}`", name, url);
+        }
+        Ok(())
+    } else {
+        bail!("Deployment not found");
```
Comment (lutter) [inline node/src/manager/commands/deploy.rs:99]: Using `DeploymentSearch` here is very clever!

I think the error message is a little terse - we should tell people what exactly they did wrong with the arguments; so maybe something like
```rust
let hash = match deployment {
  DeploymentSearch::Hash { hash, _ } => hash,
  _ => bail!("The `deployment` must be a valid IPFS hash")
};
let name = match name { .. };
if create { .. }
..
```

**Review by lutter — APPROVED** [review]

File: node/src/bin/manager.rs (hunk 1 above)
Comment (incrypto32) [reply node/src/bin/manager.rs:355]: That didn't cross my mind, just took a look at how that would turn out. We still would need to provide a NodeID when creating a new SubgraphRegistrar. 
And the default_value for the url i believe is almost always ok unless the indexer change it explicitly. So we can go with this now and update in the future?

File: node/src/manager/commands/deploy.rs (hunk 2 above)
Comment (incrypto32) [reply node/src/manager/commands/deploy.rs]: Updated

File: node/src/bin/manager.rs (hunk 1 above)
Comment (lutter) [reply node/src/bin/manager.rs:355]: Yes, let's not hold this up because of the URL; just go ahead and merge
