### PR TITLE
Big decimal

### LINKED ISSUE #720: Big Decimal Support
**Do you want to request a *feature* or report a *bug*?**
Feature

**What is the current behavior?**
Big Ints can't return fractions, so in some cases we lose precision that we need

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
Reproduction of the problem can be seen on uniswap subgraph, where we try to divide ETH price by MKR price and it returns 0 instead of `~0.270`

**What is the expected behavior?**
We get the fraction returned

I closed this issue https://github.com/graphprotocol/graph-ts/issues/34 in `graph-ts` that is related

### PR DESCRIPTION
**Pull request by leoyvens**
Closes #720.

### CODE REVIEW

File: graph/src/data/store/mod.rs [hunk 1]
```diff
@@ -164,21 +165,14 @@ impl Value {
...
-            (query::Value::Enum(e), NamedType(n)) => {
-                // Check if `ty` is a custom scalar type, otherwise assume it's
-                // just a string.
-                match n.as_str() {
-                    BYTES_SCALAR => Value::Bytes(scalar::Bytes::from_str(e)?),
-                    BIG_INT_SCALAR => Value::BigInt(scalar::BigInt::from_str(e)?),
-                    _ => Value::String(e.clone()),
-                }
-            }
+            (query::Value::Enum(e), NamedType(_)) => Value::String(e.clone()),
```
Comment (Jannis) [inline graph/src/data/store/mod.rs]: Interesting, the above didn't really make sense, huh (an enum value that represents a `Bytes` or `BigInt` value isn't even possible, since enum values don't have quotes around them like strings/bytes/bigints)?

File: graph/src/data/store/mod.rs [hunk 2]
```diff
@@ -188,8 +182,6 @@ impl Value {
                     .ok_or_else(|| QueryExecutionError::NamedTypeError("Int".to_string()))?
                     as i32,
             ),
-            (query::Value::Variable(var), _) => Value::String(var.to_owned()),
```
Comment (Jannis) [inline graph/src/data/store/mod.rs]: Is this not needed?

File: graph/src/data/store/scalar.rs [hunk 3]
```diff
@@ -9,6 +9,10 @@ use std::str::FromStr;
 
 pub use num_bigint::Sign as BigIntSign;
 
+// Caveat: The expoent is currently an i64 and may overflow.
```
Comment (Jannis) [inline graph/src/data/store/scalar.rs]: Typo: expoent -> exponent

File: graphql/tests/query.rs [hunk 4]
```diff
@@ -325,7 +325,7 @@ fn can_query_one_to_many_relationships_in_both_directions() {
         query {
             musicians(first: 100, orderBy: id) {
                 name
-                writtenSongs(first: 100) {
+                writtenSongs(first: 100, orderBy: id) {
```
Comment (Jannis) [inline graphql/tests/query.rs]: Ah, great. I think I added that in one of my branches as well.

File: runtime/wasm/src/host_exports.rs [hunk 5]
```diff
@@ -432,6 +446,38 @@ where
...
+    pub(crate) fn big_decimal_minus(&self, x: BigDecimal, y: BigDecimal) -> BigDecimal {
+        x - y
+    }
+
+    pub(crate) fn big_decimal_times(&self, x: BigDecimal, y: BigDecimal) -> BigDecimal {
+        x * y
+    }
+
+    pub(crate) fn big_decimal_divided_by(&self, x: BigDecimal, y: BigDecimal) -> BigDecimal {
+        x / y
```
Comment (Jannis) [inline runtime/wasm/src/host_exports.rs]: What happens if `y` is essentially `0`?

File: runtime/wasm/src/host_exports.rs [hunk 6]
```diff
@@ -432,6 +446,38 @@ where
...
+    pub(crate) fn big_decimal_to_string(&self, x: BigDecimal) -> String {
+        x.to_string()
+    }
+
+    pub(crate) fn big_decimal_from_string(
+        &self,
+        s: String,
+    ) -> Result<BigDecimal, HostExportError<impl ExportError>> {
+        BigDecimal::from_str(&s)
+            .map_err(|e| HostExportError(format!("Failed to parse BigDecimal: {}", e)))
```
Comment (Jannis) [inline runtime/wasm/src/host_exports.rs]: Nit: The capitalization between this error and the ```attempted to divide BigInt `{}` by zero``` is inconsistent.

File: runtime/wasm/src/to_from/external.rs [hunk 7]
```diff
@@ -58,6 +58,24 @@ impl FromAscObj<AscBigInt> for BigInt {
     }
 }
 
+impl ToAscObj<AscBigDecimal> for BigDecimal {
+    fn to_asc_obj<H: AscHeap>(&self, heap: &mut H) -> AscBigDecimal {
+        // "exponent" here is the opposite of what you'd expect.
```
Comment (Jannis) [inline runtime/wasm/src/to_from/external.rs]: Could we make this a little more specific? I found `Note that a positive exponent indicates a negative power of 10` in the `BigDecimal` docs, which made it more clear: https://docs.diesel.rs/bigdecimal/struct.BigDecimal.html#method.as_bigint_and_exponent

Comment (Jannis) [reply runtime/wasm/src/to_from/external.rs]: On another note: Is this a normal thing to do, do we know? It's so weird. 😉

**Review by Jannis — CHANGES_REQUESTED** [review]
This is looking great overall!

File: graph/src/data/store/mod.rs (hunk 1 above)
Comment (leodasvacas) [reply graph/src/data/store/mod.rs]: Yhea I understand that an enum is an unquoted string, and those can never be numbers, so it doesn't seem to make sense.

File: graph/src/data/store/mod.rs (hunk 2 above)
Comment (leodasvacas) [reply graph/src/data/store/mod.rs]: No, we should have resolved variables by now.

File: runtime/wasm/src/host_exports.rs (hunk 5 above)
Comment (leodasvacas) [reply runtime/wasm/src/host_exports.rs]: Fixed.

File: runtime/wasm/src/to_from/external.rs (hunk 7 above)
Comment (leodasvacas) [reply runtime/wasm/src/to_from/external.rs]: Don't know why the Rust library does that, it's also weird to me. I checked the Python library and it uses exponents.

File: graph/src/data/store/scalar.rs (hunk 3 above)
Comment (leodasvacas) [reply graph/src/data/store/scalar.rs]: Ha, in portuguese we don't have that `n`.

**Comment by leodasvacas** [comment]
@Jannis review addressed.

File: graph/src/data/store/mod.rs (hunk 2 above)
Comment (Jannis) [reply graph/src/data/store/mod.rs]: Ah, yes 👍

File: graph/src/data/store/scalar.rs (hunk 3 above)
Comment (Jannis) [reply graph/src/data/store/scalar.rs]: 😁

**Review by Jannis — APPROVED** [review]
