### PR TITLE
Bug fix: Fetch correct function abi from contract abi 

### LINKED ISSUE #1841: Failed call output decoding
I've now seen a few reports of subgraphs failing on this line with the message: `Generating function outputs for an Ethereum call failed: Invalid data`. The latest example being `QmabWhS38ENWDVYL3MHpF7os57yFrfEFvqE397j5Pauqoo` at https://thegraph.com/explorer/subgraph/tech-nerd/productioneip20token.

Some subgraphs were reported to have "fixed themselves" after a restart. I tried one restart for that one and it did not work.

### PR DESCRIPTION
**Pull request by fordN**
Resolves #1841 

This PR fixes a bug in `contract_function_with_signature()` which allowed for false positives to be returned. This inconsistency led to incorrect function abis being used in function param decoding leading to `invalid data` errors in [ethabi](https://github.com/graphprotocol/ethabi). 

I've also restructured `contract_function_with_signature()` to reduce unnecessary work building function signature hashes for functions that can be excluded early because they are `view` or `pure` functions.

### CODE REVIEW

**Review by leoyvens — APPROVED** [review]

File: graph/src/util/ethereum.rs [hunk 1]
```diff
@@ -123,20 +123,24 @@ pub fn contract_function_with_signature<'a>(
     target_signature: &str,
 ) -> Option<&'a Function> {
     contract.functions().find(|function| {
```
Comment (leoyvens) [inline graph/src/util/ethereum.rs:125]: Actually this would be better if we checked the mutability in a call to `filter`. Also we should do an exhaustive match on all variants, for better future proofing.

**Review by leoyvens — CHANGES_REQUESTED** [review]
Actually I have a request.

**Review by leoyvens — APPROVED** [review]

**Comment by stevepro-lab** [comment]
Hey @fordN  @leoyvens 
This fix is available in hosted service now?
