### PR TITLE
graph: fix substreams `startBlock` selection

### LINKED ISSUE #4449: Picking `startBlock` for substreams data source
[This logic](https://github.com/graphprotocol/graph-node/blob/860becc40e9d4350adc1372e430f354c3ae18727/chain/substreams/src/data_source.rs#L175-L178) of picking the startBlock for the module to stream, where we pick the MIN `initial_block` among **all** modules in the package, seems superfluous and wrong.

For some complex substreams it could pick wrong block values resulting in indexing errors like this:
```
An error occurred while streaming blocks: status: InvalidArgument, message: "start block 100000 smaller than request outputs for module \"graph_out\" with start block 1000000"
```

IMO We should just take the `initial_block` of the module being requested.

`substreams pack` already assigns initial_block for modules that don't have `initial_block` set, based on its ancestors, so trying to silently override it here seems unnecessary.

### PR DESCRIPTION
**Pull request by YaroShkvorets**
This fixes #4449 by choosing `initial_block` of the module provided in the manifest.

It also verifies that module name provided in the subgraph manifest exists in the substreams manifest and if not, `graph deploy` errors out rather than letting it deploy and then unsuccessfully retry RPC requests to the substreams endpoint.

### CODE REVIEW

**Comment by YaroShkvorets** [comment]
Oh. Making it pass those tests would be non-trivial without the substreams package...

**Comment by YaroShkvorets** [comment]
Ready for review

File: chain/substreams/src/data_source.rs [hunk 1]
```diff
@@ -340,14 +346,35 @@ mod test {
...
+            modules: Some(graph::substreams::Modules {
+                modules: vec![graph::substreams::Module {
+                    name: "output".into(),
+                    initial_block: 123,
+                    binary_entrypoint: "entry".into(),
+                    binary_index: 0,
+                    kind: None,
+                    inputs: vec![],
+                    output: None,
+                }],
```
Comment (maoueh) [inline chain/substreams/src/data_source.rs:362]: Actually, could you add a second module with a different block so we see the code is working properly.

**Review by maoueh — CHANGES_REQUESTED** [review]

**Review by maoueh — APPROVED** [review]
Once the tests pass, I'll merge this.
