### PR TITLE
Fix oneshot cancelled errors

### LINKED ISSUE #2797: Improve error message for runtime panics (`oneshot canceled`)
Nowadays when the `runtime` code panics before the mappings code, we save something like this to the `SubgraphErrors` table:

```
Subgraph instance failed to run: failed to process trigger: block #15730765 (0x3fc4…457f), transaction f7fd51db1b13c53b571d767503af8d6ad946708fe8ff67de8bceab3dd30f69d6: Mapping terminated before handling trigger: oneshot canceled, code: SubgraphSyncingFailure
```

The message `Mapping terminated before handling trigger: oneshot canceled` is actually an `anyhow` context ([that happens here](https://github.com/graphprotocol/graph-node/blob/master/runtime/wasm/src/host.rs#L195)) of `Mapping terminated before handling trigger` with `oneshot canceled`, which is the panic from the channel.

Maybe look [here](https://github.com/graphprotocol/graph-node/blob/master/runtime/wasm/src/mapping.rs#L54).

- [ ] Investigation on where exactly we're losing the error message
- [ ] Implement the solution

### PR DESCRIPTION
**Pull request by incrypto32**
Fixes #2797

### CODE REVIEW

File: runtime/wasm/src/mapping.rs [hunk 1]
```diff
@@ -52,14 +53,32 @@ where
...
+                    );
+
+                    panic!("TEST PANIC");
+                    result
+                }));
+
+                let result = match result {
+                    Ok(result) => result,
+                    Err(panic_info) => {
+                        let err_msg = if let Some(payload) = panic_info.downcast_ref::<&str>() {
```
[the remark this answers is not in the document]
Comment (incrypto32) [reply runtime/wasm/src/mapping.rs:73]: gotcha

File: runtime/wasm/src/mapping.rs [hunk 2]
```diff
@@ -52,14 +53,33 @@ where
...
+                        let err_msg = if let Some(payload) = panic_info
+                            .downcast_ref::<String>()
+                            .map(String::as_str)
+                            .or(panic_info.downcast_ref::<&str>().copied())
+                        {
+                            anyhow!("Subgraph panicked with message: {}", payload)
+                        } else {
+                            anyhow!("Subgraph panicked with an unknown payload.")
+                        };
+                        println!("Subgraph panicked with message: {}", err_msg);
```
Comment (leoyvens) [inline runtime/wasm/src/mapping.rs:79]: Usually we don't want `println!` in the code, we could turn this into a log but it seems just redundant with the error, lets remove this.

**Review by leoyvens — CHANGES_REQUESTED** [review]

File: runtime/wasm/src/mapping.rs (hunk 2 above)
Comment (incrypto32) [reply runtime/wasm/src/mapping.rs]: Got it, will keep that in mind going forward, addressed the changes

**Review by leoyvens — APPROVED** [review]
