### PR TITLE
fix(graphql): include introspection fields in error

### LINKED ISSUE #2443: Introspection queries stop working after a subgraph has encountered an indexing error
**Do you want to request a *feature* or report a *bug*?**
bug

**What is the current behavior?**
Introspection queries fail after a subgraph has encountered an indexing error.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
This potentially also happens if the subgraph flat fails (not sure) but we encountered it whilst using the nonFatalErrors feature. Hence:

1. Deploy a failing subgraph using the nonFatalErrors feature
2. Wait for it to fail and then try to run a schema introspection or type query
3. The query returns `message: indexing_error`

**What is the expected behavior?**
Even if a subgraph has failed, introspection queries should always work (both when using the nonFatalErrors feature or not). The schema is immutable and not affected by any indexing errors.

The `__schema` and `__type` fields are part of the spec and used by various tooling. Hence, adding a `subgraphErrors: allow` input field to those fields wouldn't work well. Instead, both `__type` and `__schema` should simply always work.

### PR DESCRIPTION
**Pull request by saihaj**
include `__schema` and `__type` part of the result when there is an indexing error and the error policy is deny.

Fixes #2443

----

There is another issue I found (could just be how tests are setup) but I wasn't really able to fix. In the example below if there is an indexing error this will return `null` but I would imagine that we return partial result i.e. `__schema` is returned in the `data` 
```graphql
query { musician(id: "m1") { id } __schema { queryType { name } } }
```

### CODE REVIEW

File: graphql/src/store/resolver.rs [hunk 1]
```diff
@@ -382,12 +382,36 @@ impl Resolver for StoreResolver {
...
+                let meta_fields = data.as_mut().and_then(|d| {
+                    let meta_field = d.remove("_meta");
+                    let schema_field = d.remove("__schema");
+                    let type_field = d.remove("__type");
+
+                    // combine the fields into a vector
+                    let mut meta_fields = Vec::new();
+
+                    if let Some(meta_field) = meta_field {
+                        meta_fields.push((Word::from("_meta"), meta_field));
```
Comment (mangas) [inline graphql/src/store/resolver.rs:397]: can we move these magic values to constants?

**Comment by mangas** [comment]
LGTM but I'd rather @lutter also reviews

**Review by lutter — APPROVED** [review]

**Comment by lutter** [comment]
@saihaj Can you rebase once more? CI is now actually stable and we should then be able to merge this finally
